// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQouW3I-bWLaJuGWlgb0mTXy_EHDYXfys',
    appId: '1:950341969594:android:5bd412781b806b9f394483',
    messagingSenderId: '950341969594',
    projectId: 'feed-app-c0506',
    storageBucket: 'feed-app-c0506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAkZpl29v4tnuO21J-4wNAHgmUKHkmAv8',
    appId: '1:950341969594:ios:2667790969e843b1394483',
    messagingSenderId: '950341969594',
    projectId: 'feed-app-c0506',
    storageBucket: 'feed-app-c0506.firebasestorage.app',
    androidClientId: '950341969594-9c4bdq32tohi97a4ruh245bn8knd5jr4.apps.googleusercontent.com',
    iosClientId: '950341969594-dsuel7q4dcc6j30300enae66ui4t8e8q.apps.googleusercontent.com',
    iosBundleId: 'com.app.feedApp',
  );

}