name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.8'
      
  
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build apk
        run: flutter build apk
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: apk-release
            path: build/app/outputs/flutter-apk/app-release.apk
